### ISSUE TITLE
PXL.XML ':' or '-' not accepted in Attribute-Names

### ISSUE THREAD

**Issue by michael-ring** [yunkot/pxl#1]
First of all, your XML class is something I have been long wanting to have, no pointer chaos, everything is very easy to debug in the delphi IDE, many thanks!

I found one issue:

I cannot parse xml files that have attribute names with a ':'
This is something very common so it would be nice if you could change the parser.
I hacked PXL.XML to accept ':' but a clean solution would be better:

function IsNameCharacter(const ScanCh: Char): Boolean;
begin
  Result := (not (ScanCh in XWhiteSpace)) and (not (ScanCh in XSeparators));
  if (Result = false) and (ScanCH = ':') then
    Result := true;
end;

Example:

 <package xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
         xmlns:saxon="http://saxon.sf.net//"
         schemaVersion="1.3"

**Comment by michael-ring** [comment]
Another issue is with '-', this is also a valid entry for attribute names
So I canged code to:
  if (Result = false) and ((ScanCH = ':') or (ScanCH = '-')) then

**Comment by yunkot** [comment]
Thank you for reporting this, I'll look into these changes. One thing to watch for is whether the aforementioned changes would allow invalid tags such as <:sometext field="test" /> (non-validated first letter).

**Comment by michael-ring** [comment]
I did not try to completely understand your code, just tried to do a fix that is as local as possible, so it is a good idea to verify my changes with your background on how the code is supposed to work..

**Comment by yunkot** [comment]
Fixed in commit b1fcc97b1187b0a3c0a6e5dc2314eb64a29d6f4b.
